version: '3.8'

services:
  tms-app:
    build: .
    ports:
      - "9090:80"
    depends_on:
      - mysql
    networks:
      - tms-net

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tmsdb
      MYSQL_USER: tmsuser
      MYSQL_PASSWORD: tmspass
    networks:
      - tms-net

networks:
  tms-net:
